import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/providers/react-query-provider";
import Header from "./_components/header/header";
import { Footer } from "./_components/footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark`}
    >
      <body
        className={`antialiased grid grid-rows-[20px_1fr_20px] items-center justify-items-center h-screen`}
      >
        <QueryProvider>
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
