import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/providers/react-query-provider";
import Header from "./_components/header/header";
import SidebarDrawer from "./_components/sidebar/sidebar-drawer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark`}
    >
      <body className={`antialiased flex w-full`}>
        <QueryProvider>
          <section className="hidden md:block h-screen sticky top-0">
            <SidebarDrawer />
          </section>
          <section className="flex-1 flex flex-col min-h-screen">
            <Header />
            <main className="">{children}</main>
          </section>
        </QueryProvider>
      </body>
    </html>
  );
}
